// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mtg.Data;

#nullable disable

namespace mtg.Migrations
{
    [DbContext(typeof(MTGContext))]
    [Migration("20251112170414_ColunaUsuarioEUsuarioCartas")]
    partial class ColunaUsuarioEUsuarioCartas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mtg.Api.Models.Cartas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCor")
                        .HasColumnType("integer")
                        .HasColumnName("idcor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IdCor");

                    b.ToTable("cartas");
                });

            modelBuilder.Entity("mtg.Api.Models.Cores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("CoresCarta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cores");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("cores");
                });

            modelBuilder.Entity("mtg.Api.Models.UsuarioCartas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaId")
                        .HasColumnType("integer")
                        .HasColumnName("cartaId");

                    b.Property<int?>("CartasId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioId");

                    b.Property<int?>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartasId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("usuarioCartas");
                });

            modelBuilder.Entity("mtg.Api.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("mtg.Api.Models.Cartas", b =>
                {
                    b.HasOne("mtg.Api.Models.Cores", "Cores")
                        .WithMany("Cartas")
                        .HasForeignKey("IdCor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cores");
                });

            modelBuilder.Entity("mtg.Api.Models.UsuarioCartas", b =>
                {
                    b.HasOne("mtg.Api.Models.Cartas", "Cartas")
                        .WithMany("UsuarioCarta")
                        .HasForeignKey("CartasId");

                    b.HasOne("mtg.Api.Models.Usuarios", "Usuarios")
                        .WithMany("UsuarioCarta")
                        .HasForeignKey("UsuariosId");

                    b.Navigation("Cartas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("mtg.Api.Models.Cartas", b =>
                {
                    b.Navigation("UsuarioCarta");
                });

            modelBuilder.Entity("mtg.Api.Models.Cores", b =>
                {
                    b.Navigation("Cartas");
                });

            modelBuilder.Entity("mtg.Api.Models.Usuarios", b =>
                {
                    b.Navigation("UsuarioCarta");
                });
#pragma warning restore 612, 618
        }
    }
}
